name: saluone_native_splash
description: For change your splashscreen in flutter.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0
  flutter: ">=2.5.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.4
  image: ^4.1.7
  meta: ^1.11.0
  path: ^1.9.0
  universal_io: ^2.2.2
  xml: ^6.5.0
  yaml: ^3.1.2
  ansicolor: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        package: com.saluone.saluone_native_splash
        pluginClass: SaluoneNativeSplashPlugin
      ios:
        pluginClass: SaluoneNativeSplashPlugin
      web:
        pluginClass: SaluoneNativeSplashWeb
        fileName: saluone_native_splash_web.dart